version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sialorama
      MONGO_INITDB_ROOT_PASSWORD: secret123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  app:
    build: .
    container_name: employee-app
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION=mongodb://sialorama:secret123@mongo:27017/
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge
