apiVersion: v1
kind: Service
metadata:
  name: knode
spec:
  selector:
    app: knode
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 3000  # Internal port of your container
  type: LoadBalancer  # Exposes the service externally (use ClusterIP for internal-only)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knode
  template:
    metadata:
      labels:
        app: knode
    spec:
      containers:
        - name: knode
          image: sialorama/knode:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/dev
          imagePullPolicy: Always