apiVersion: v1
kind: Service
metadata:
  name: kubenode
spec:
  selector:
    app: kubenode
  ports:
    - protocole: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubenode
  template:
    metadata:
      labels:
        app: kubenode
    spec:
      containers:
        - name: kubenode
          image: sialorama/kubenode:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/dev
          imagePullPolicy: Always